org: imronpuji
app: lambda
service: lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: '*'
